spring:
  config:
    import: 'classpath:database.yaml'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple-sns
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    url: ${redis.url}

jwt:
  secret-key: com.simple.app.simple-sns-service-2024.secret_key
  token:
    expired-time-ms: 2592000000 # 30 days
