### get likes
GET http://localhost:8080/api/v1/posts/2/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNzA1MzgwMDY2LCJleHAiOjE3MDc5NzIwNjZ9.XDsbr4dYSRSj_uAT7EmLxVg6k_JEQD51K9uxGMf7jGk

### post likes
POST http://localhost:8080/api/v1/posts/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6InJheWluZm8iLCJpYXQiOjE3MDU0Njg1MjksImV4cCI6MTcwODA2MDUyOX0.rjMlitzkQ_d1fZtVx4rtMpzcneHE9Oq5Cbho8kopXQQ
Content-Type: application/json

### get comments
GET http://localhost:8080/api/v1/posts/2/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNzA1MzgwMDY2LCJleHAiOjE3MDc5NzIwNjZ9.XDsbr4dYSRSj_uAT7EmLxVg6k_JEQD51K9uxGMf7jGk

### post comments
POST http://localhost:8080/api/v1/posts/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6InJheWluZm8iLCJpYXQiOjE3MDU0Njg1MjksImV4cCI6MTcwODA2MDUyOX0.rjMlitzkQ_d1fZtVx4rtMpzcneHE9Oq5Cbho8kopXQQ
Content-Type: application/json

{
  "comment": "sseEmitter test comment"
}

### get posts
GET http://localhost:8080/api/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNzA1MzgwMDY2LCJleHAiOjE3MDc5NzIwNjZ9.XDsbr4dYSRSj_uAT7EmLxVg6k_JEQD51K9uxGMf7jGk

### post posts
POST http://localhost:8080/api/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNzA1MzgwMDY2LCJleHAiOjE3MDc5NzIwNjZ9.XDsbr4dYSRSj_uAT7EmLxVg6k_JEQD51K9uxGMf7jGk
Content-Type: application/json

{
  "title": "This is admin title1",
  "body": "this is admin body1"
}

### delete posts
DELETE http://localhost:8080/api/v1/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNzA1MzgwMDY2LCJleHAiOjE3MDc5NzIwNjZ9.XDsbr4dYSRSj_uAT7EmLxVg6k_JEQD51K9uxGMf7jGk
